//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC_Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialOrderDetail
    {
        public int MaterialOrderDetailId { get; set; }
        public int MaterialId { get; set; }
        public int MaterialQuantity { get; set; }
        public int MaterialOrderId { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual MaterialOrder MaterialOrder { get; set; }
    }
}
