//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC_Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialOrderDetails = new HashSet<MaterialOrderDetail>();
        }
    
        public int MaterialId { get; set; }
        public string Name { get; set; }
        public int CatagoryId { get; set; }
        public decimal Price { get; set; }
    
        public virtual MaterialCatagory MaterialCatagory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialOrderDetail> MaterialOrderDetails { get; set; }
    }
}
