//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC_Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.OrderMenuDetials = new HashSet<OrderMenuDetial>();
        }
    
        public int DishId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int DishCatagoryId { get; set; }
        public string Descripition { get; set; }
    
        public virtual DishType DishType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMenuDetial> OrderMenuDetials { get; set; }
    }
}
